### ISSUE TITLE
Board dimensions / connector footprint

### ISSUE THREAD

**Issue by bluecube** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#40]
Hi,
I'd like to make  a "hat" PCB for this board, It would be nice to have a drawing with dimensions, to not have to measure it manually. Even nicer would be a KiCad footprint :-)

**Comment by quakec** [comment]
Assuming you use KiCad...

[LILYGO POE HAT.zip](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/files/12110470/LILYGO.POE.HAT.zip)

**Comment by quakec** [comment]
> awesome, thank you!

I measured it manually just for you :)
Let me know how it goes.
