### ISSUE TITLE
Enhancement Request:  Add 5v Pin for sensors that require it

### ISSUE THREAD

**Issue by lschapker** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#42]
Hello I'm looking to use a mmWave sensor and based on the spec sheet, it requires 5V.  It would be extremely handy to have a pin available to supply 5V to sensors instead of attempting to "splice" one in.
Thank you!

**Comment by raomin** [comment]
+1

**Comment by HotNoob** [comment]
+1
