### ISSUE TITLE
Where to buy the T-ETH-LITE-ESP32S3

### ISSUE THREAD

**Issue by jonasniesner** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#43]
I have not found this board on the website yet. This board looks like a perfect fit for a project of mine. Is there a timeline when it and the Poe add-on board will be available (preferably on AliExpress)?

**Comment by quakec** [comment]
> I have not found this board on the website yet. This board looks like a perfect fit for a project of mine. Is there a timeline when it and the Poe add-on board will be available (preferably on AliExpress)?

Are you referring to this board:

Just found this amazing item on AliExpress. Check it out! ￡5.73 | LILYGO® TTGO T-Lite W5500 ESP32 Master Chip SSD1306 0.96-inch OLED Type-C USB Programming Board WiFi Bluetooth Wireless Module
https://a.aliexpress.com/_mO1D9Py

**Comment by lewisxhe** [comment]
There is currently no sales going on, we need to wait for a period of time

**Comment by jonasniesner** [comment]
Ok, is there a way to get informed when the board is available for sale? Is the design of the board final, so I can start the design of a hat for it?

**Comment by lewisxhe** [comment]
If it is sold, I will notify you here. Regarding other design resources, I have made it public. You can view the structure size in the shell directory, and the schematic directory has schematic diagrams

**Comment by lewisxhe** [comment]
Currently available for purchase, please check https://www.lilygo.cc/products/t-eth-lite?variant=43120880779445
