### ISSUE TITLE
T-Internet-POE LED PIN

### ISSUE THREAD

**Issue by henriberisha** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#46]
Hello LilyGO! Firstly i want to congratulate you for your amazing products! 
I recently purchased "T-Internet-POE" ESP32. I wanted to ask if there is a pin that controls the Blue LED. 

Thank you, all the best!

**Comment by lewisxhe** [comment]
It cannot be turned off, it is a power indicator

**Comment by henriberisha** [comment]
Thank you!
