### ISSUE TITLE
Direct connection between ESP32 and PC

### ISSUE THREAD

**Issue by bestautomation-vim** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#50]
Hello Team,
We have executed example from https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/tree/master/examples/TCPServer
We have 2 cases: 
**Case-1:** 
ESP32==> Router==> PC
All works well. All switch cases executed in code. 

**case-2:**
ESP32==>  PC
 we are not able establish direct connection between ESP32 & PC. 
Code is not executing from case ARDUINO_EVENT_ETH_GOT_IP:. 
Its only printing, ETH Connected.

Your support needed to  resolve this issue.

**Comment by lewisxhe** [comment]
If you do not use an intermediate route, you need to configure static addresses on both the computer and ETH-lite, because there is no intermediate route to assign IP addresses. I wrote a simple test example and recorded a test video. I hope it can help you.
https://youtu.be/fH_CvnUJu2A

**Comment by drewsed** [comment]
Same issue with T-internet-poe. Static IP will not get assigned.

**Comment by drewsed** [comment]
Ok, the hello server example is the only one where ETH.config() is executed before ETH.begin().

Swapping those lines leads to a static ip.
