### ISSUE TITLE
Lilygo T-ETH lite ESP32S3 ACT,POWER, LINK leds

### ISSUE THREAD

**Issue by Nezhit** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#57]
I have board t-eth lite esp32s3, on this board there are 3 leds: ACT,POWER,LINK with green, yellow, red colors. What GPIOS do controll them? Can i program any them for my goals by code (e.g. make link or act led blink when i call function)

**Comment by lewisxhe** [comment]
cannot be controlled
