### ISSUE TITLE
T-ETH Lite : how much current can I draw?

### ISSUE THREAD

**Issue by fplanque** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#71]
In #69 , you linked to the PoE module that can output 12.95 W to the board.

This is impressive, but I believe I cannot actually draw that much power for my additional sensors/actuators, right?

Can you please specify:

- How much current I can draw from the 5V pin on the T-ETH Lite board? (in A or mA)
- How much current I can draw from the 3.3V pin on the T-ETH Lite board? (in A or mA)
- How much current I can draw from the I/O pins? (in mA)

Thank you.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/assets/22990954/90283e91-4bd9-4860-b0c5-dc61acfc6487)
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/assets/22990954/7de2631a-9a51-4bd6-bc3f-71b470815e07)
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/assets/22990954/40c4db27-0edf-41c8-ac95-8c413578d35e)

**Comment by lewisxhe** [comment]
According to actual tests, it is recommended that the 3.3V/5V load be controlled at around 500mA. Excessive load will increase the POE temperature.

**Comment by fplanque** [comment]
> According to actual tests, it is recommended that the 3.3V/5V load be controlled at around 500mA. Excessive load will increase the POE temperature.

I was expecting a limitation anywhere else but not in the PoE module.
That PoE module is rated for 12.95 W, right ?
So even if I draw 3.3*0.8=2.64 W + 5*0.8 = 4 W, I am still drawing only 6.64 Watts.
So the PoE module should be able to handle that heat, no?

Or is there another part of the PoE shield that is not well rated for 12.95W ?

Thank you.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/assets/22990954/d0e4c389-6a4e-44d9-b22e-1a47b8fc8aee)

No! Not 12.95W, POE output 5V, the maximum power can only reach 9W, when the temperature reaches 85° the power drops to 6W (1.2A)

**Comment by fplanque** [comment]
Ah, thank you for clarifying that !!

So assuming I have enough airflow to maintain the PoE shield at or below 70°C, can I safely draw about 8 W (leaving 1W for the board) from the 5V and/or 3.3V pins of the T-ETH-Lite board? For example 2.4 A from the 3.3V pin (and 0A from 5V)?

Or are there additional limitations inducted by the circuits on the T-ETH-Lite board?

Thank you.

**Comment by lewisxhe** [comment]
1W is far from enough. The maximum current drawn by ESP32 is about 800mA. 3.3V can provide up to 800mA to work stably. It is recommended that the maximum current of 5V Pin should not exceed 800mA.
