### ISSUE TITLE
T-ETH-Lite-S3 W5500 - can I accress USB d+ and USB d- as I would be able to on a typical ESP32-S3 board?

### ISSUE THREAD

**Issue by imfatant** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#77]
Regarding the T-ETH-Lite-S3 W5500,  can I access USB d+ and USB d- as I would be able to on a typical ESP32-S3 board?

I want to be able to reconfigure the USB interface using TinyUSB! (Pretty normal kinda thing to want to do.)

By default, USB d+ is on GPIO 20, and USB d- is on GPIO 19. I believe.

Thanks,

-- Anthony

**Comment by lewisxhe** [comment]
Of course, the 19 and 20 GPIOs of the board are directly connected to the chip

**Comment by imfatant** [comment]
Thank you,
It's resolved in my mind :)
