### ISSUE TITLE
Network connection

### ISSUE THREAD

**Issue by bluey1** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#78]
How do i get the ESP32  RJ45 connector enabled ? and connect the ESP32 to my PC? Thanks.
When I plug in a network cable I get no network lights.

**Comment by lewisxhe** [comment]
Write examples, such as [UnitTestExample](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/tree/master/examples/UnitTestExample), and then plug in the network cable. You should be able to see the network light.

**Comment by bluey1** [comment]
OK tks I will try that
