### ISSUE TITLE
Example usb_cdc_4g_module not working!

### ISSUE THREAD

**Issue by ruslanslobozhenuk** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#82]
Not correct init modem (((

[lte.log](https://github.com/user-attachments/files/16744781/lte.log)

[lte1.txt](https://github.com/user-attachments/files/16744907/lte1.txt)

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/4124fd7a-cd80-4b45-9020-281519313f2c)
Confirm that the endpoint address is as shown in the figure below
