### ISSUE TITLE
STEP or DXF file for the eth-lite pcb

### ISSUE THREAD

**Issue by kquinsland** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#86]
Hi. Similar to https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/issues/9. Can you please share at least a 2d dimensions file for the module?  I am trying to create a KiCAD symbol and footprint for a breakout pcb.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/tree/master/shell
