### ISSUE TITLE
T-ETH-Lite Datasheet

### ISSUE THREAD

**Issue by programmeddeath1** [Xinyuan-LilyGO/LilyGO-T-ETH-Series#88]
Is there a datasheet available for the T-ETH-LITE ESP32-S3 module with the specs regarding the ethernet speeds on the W5500 chip? I can only see datasheet for the POE chips in the github.

Thanks in advance!

**Comment by lewisxhe** [comment]
Here is the manual for W5500 https://wiznet.io/products/iethernet-chips/w5500
